# Kronos Live Forecast Configuration
# 配置文件：设置模型参数、采样参数和数据源

model:
  model_name: "Kronos-base"  # 可选: "Kronos-small" (24.7M) 或 "Kronos-base" (102.3M)
  tokenizer_name: "Kronos-Tokenizer-base"
  model_path: "../Kronos_model"  # 外部模型存储路径
  max_context: 512
  device: "cpu"  # 可选: "cpu" 或 "cuda"

sampling:
  temperature: 0.6  # 温度参数，控制预测随机性 (0.1-1.0) 推荐-0.6
  top_p: 0.9       # Top-p采样参数 (0.1-1.0)  推荐-0.9
  num_samples: 30  # 蒙特卡洛采样次数 (建议: 10-50) 推荐-30
  volatility_temperature_multiplier: 1.0  # 波动性预测温度倍数，1.0表示一次预测，>1.0表示两次预测
  
  # 随机种子配置 - 确保结果可重现
  random_seed: 42  # 固定随机种子，确保每次运行结果一致
  enable_deterministic: true  # 启用确定性模式，减少随机性

data:
  symbol: "ETHUSDT"      # 交易对符号
  timeframe: "1h"        # 时间间隔 (1h, 4h, 1d等)
  history_window: 360    # 历史数据窗口 (小时数， 最大 512) 默认-360
  forecast_horizon: 4   # 预测时间范围 (小时数) 默认-24
  volatility_window_multiplier: 1.0  # 波动率窗口倍率 (相对于forecast_horizon) 默认-1.0
  cache_enabled: true    # 启用数据缓存
  cache_max_age_hours: 1 # 缓存数据最大年龄 (小时)
  cache_dir: "data"      # 缓存目录
  update_mode: "auto"    # 更新模式: "auto", "force", "cache_only"

api:
  binance_base_url: "https://api.binance.com"  # 币安API基础URL
  request_timeout: 30     # 请求超时时间 (秒)
  retry_attempts: 3       # 重试次数

output:
  chart_filename: "prediction_chart.png"
  html_filename: "index.html"
  auto_commit: false      # 是否自动提交Git更新 (false=完全禁用Git操作)
  auto_push: false        # 是否自动推送到远程仓库 (默认false，仅本地提交)
  web_server_port: 8000   # 本地Web服务器端口

logging:
  level: "INFO"           # 日志级别: DEBUG, INFO, WARNING, ERROR
  enable_file_logging: false  # 是否启用文件日志

validation:
  enable_metrics_validation: true   # 启用12个增强指标数学验算
  show_validation_details: true    # 显示详细验算过程
  stop_on_validation_error: false  # 验算错误时停止运行
  
  # 自适应容差配置
  tolerance_strategy: "adaptive"   # fixed | adaptive | per_metric
  validation_tolerance: 0.00015    # 验算容差 (验算器实际使用的参数)
  default_tolerance: 0.00015       # 默认容差 (兼容性保留)
  
  # 针对confidence_score的特殊容差设置
  confidence_score_tolerance: 0.00015  # 专门针对置信度指标的容差
  
  # 按指标类型设置容差
  tolerance_by_type:
    probability: 0.0001           # 概率指标 (相对容差)
    percentage: 0.01              # 百分比指标 (绝对容差)  
    score: 1.0                    # 评分指标 (整数容差)
    ratio: 0.001                  # 比例指标 (对数容差)
  
  # 特定指标容差覆盖
  metric_specific_tolerance:
    vol_persistence_score: 0.01   # 波动持续性评分容差放宽
    overall_vol_risk_score: 2.0   # 综合风险评分允许2分误差
    avg_amplification_factor: 0.1 # 平均放大倍数容差

